#!/bin/sh


#these envs below should be export by manual:
# LDAP_HOST_ADDR
# LDAP_ADMIN_USER
# LDAP_ADMIN_PASSWORD
# LDAP_BASE_DN
# ETCDPREFIX

# ADMIN_EMAIL
# ADMIN_EMAIL_PASSWORD
# EMAIL_SERVER_HOST
# EMAIL_SERVER_PORT

export ETCD_HTTP_ADDR=${BSI_ETCD_PROXYETCD_URI}
export ETCD_USERNAME=${BSI_ETCD_PROXYETCD_USERNAME}
export ETCD_PASSWORD=${BSI_ETCD_PROXYETCD_PASSWORD}

oauth-proxy
