#!/bin/sh


#these envs below should be export by manual:
# LDAP_HOST_ADDR
# LDAP_ADMIN_USER
# LDAP_ADMIN_PASSWORD
# LDAP_BASE_DN
# ETCDPREFIX

# ADMIN_EMAIL
# ADMIN_EMAIL_PASSWORD
# EMAIL_SERVER_HOST
# EMAIL_SERVER_PORT


# BSI_MYSQL_MYSQLBSI_URI
# BSI_MYSQL_MYSQLBSI_NAME
# BSI_MYSQL_MYSQLBSI_USERNAME
# BSI_MYSQL_MYSQLBSI_PASSWORD
# BSI_MYSQL_MYSQLBSI_HOST
# BSI_MYSQL_MYSQLBSI_PORT
# ENV_NAME_MYSQL_ADDR=BSI_MYSQL_MYSQLBSI_HOST
# ENV_NAME_MYSQL_DATABASE=BSI_MYSQL_MYSQLBSI_NAME
# ENV_NAME_MYSQL_PASSWORD=BSI_MYSQL_MYSQLBSI_PASSWORD
# ENV_NAME_MYSQL_PORT=BSI_MYSQL_MYSQLBSI_PORT
# ENV_NAME_MYSQL_USER=BSI_MYSQL_MYSQLBSI_USERNAME


export ETCD_HTTP_ADDR=${BSI_ETCD_PROXYETCD_URI}
export ETCD_USERNAME=${BSI_ETCD_PROXYETCD_USERNAME}
export ETCD_PASSWORD=${BSI_ETCD_PROXYETCD_PASSWORD}

cd /home
oauth-proxy
