
CREATE TABLE IF NOT EXISTS DF_MESSAGE
(
   MESSAGE_ID         BIGINT NOT NULL AUTO_INCREMENT,
   TYPE               CHAR(16) NOT NULL,
   STATUS             TINYINT,
   LEVEL              TINYINT NOT NULL DEFAULT 0,
   TIME               DATETIME COMMENT '创建时间',
   RECEIVER           VARCHAR(64) NOT NULL,
   SENDER             VARCHAR(64) NOT NULL,
   HINTS              VARCHAR(64) NOT NULL DEFAULT '',
   DATA               TEXT COMMENT 'json format, 具体内容取决于type',
   PRIMARY KEY (MESSAGE_ID)
)  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
)  DEFAULT CHARSET=UTF8;

